### ISSUE TITLE
v.1.5 examples: ZE12 Referential Status

### ISSUE THREAD

**Issue by Jamafie** [swiss-art-research-net/crmaaa#24]
'Let's Go, Brandon', not an E89, but a E33?

**Comment by Habennin** [comment]
sure, generally, I think that crmbase here is wrong. 

It makes the proposition the thing that does the referring. This is problematic however as propositions cannot change. So this means that propositions always must refer the same way and unambiguosly. But clearly that is not so. It is actually the sign that signifies and the sign is the symbol / the encoded object. We change what the sign refers  to and what proposition it is meant to encode. 

But that means rewriting CRMbase....
