### ISSUE TITLE
Promisory Status – ZE45

### ISSUE THREAD

**Issue by Habennin** [swiss-art-research-net/crmaaa#40]
The subject is supposed to be... a future event? Should that then be a formulation in the CRMcpr sense? or direct to an event trigger. There is some awkwardness in that E54 Dimension is not a subclass of a proposition, but meh what ontologiclaly is dimension anyhow? Very unclear.

the naming of the properties is not consistent with obligation.

Presuming that promisory status is a superclass of obligation status.

**Comment by Jamafie** [comment]
properties are mixed up in ontome

**Comment by Habennin** [comment]
can you fix em? I thought I did honestly but if not, just change em?

**Comment by Habennin** [comment]
to me they look good

<img width="1255" alt="Screenshot 2024-10-23 at 6 03 57 PM" src="https://github.com/user-attachments/assets/e49cd1bd-e309-4d40-b803-978fc4c1b7ac">

https://ontome.net/class/1777/namespace/120

**Comment by Jamafie** [comment]
props need review
