### ISSUE TITLE
need to load crmtext in the crmaaa on ontome

### ISSUE THREAD

**Issue by Jamafie** [swiss-art-research-net/crmaaa#41]
@Habennin

**Comment by Jamafie** [comment]
ditto for CRMcpr

**Comment by Habennin** [comment]
ok I should show you how to do this it's super easy.

**Comment by Habennin** [comment]
I have added it. 

So you should be in edit mode for the namespace

Then you go to identification

Then you click edit

Then at the bottom of the screen there is a pick namespace dropdown. Pick the namespace. Add it. Done.

Make sure that they are compatible (ie don't mix versions that mix versions of crm like 7.1.3. and 6.1.2 or you get chaos.

![Uploading Screenshot 2024-10-23 at 6.06.32 PM.png…]()

**Comment by Habennin** [comment]
<img width="1202" alt="Screenshot 2024-10-23 at 6 06 16 PM" src="https://github.com/user-attachments/assets/31f39106-736a-4a37-a1b6-34ca95ad28fd">
